development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  username: root
  password: root
  database: dooxoo_www_development
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  encoding: utf8
  database: dooxoo_www_test
  host: localhost
  username: root
  password: stupidxie
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  username: dooxoo
  password: 1zhiduxoo
  database: dooxoo_www_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
